name: Pull Request on Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feature/github-workflow

jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - name: ‚¨áÔ∏è Check out repository code
        uses: actions/checkout@v3
      - name: üì¶ Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - id: versionCheck
        uses: EndBug/version-check@v2
        with:
          file-url: https://unpkg.com/experimental-bahmni-next-ui@latest/package.json
          static-checking: localIsNew
      - name: Yes Version has changed
        if: steps.versionCheck.outputs.changed == 'true'
        run: echo "The version being deployed has changed"
      - name: Publish
        if: steps.versionCheck.outputs.changed == 'true'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Publishing..."
          yarn publish --new-version ${{ steps.versionCheck.outputs.version }}
