name: Pull Request on Main

on:
  pull_request:
    branches:
      - main

jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - name: ‚¨áÔ∏è Check out repository code
        uses: actions/checkout@v3
      - name: üì¶ Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - id: versionCheck
        name: Check if version has been updated
        uses: EndBug/version-check@v2
        with:
          file-url: https://unpkg.com/experimental-bahmni-next-ui@latest/package.json
          static-checking: localIsNew
      - name: Version guard
        if: steps.versionCheck.outputs.changed == 'false'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('No version change detected. You should run `yarn bump:<patch|minor|major>` to bump the version before raising PR to main')